name: Daily OXFUN Vault and Analyse Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main  # Adjust this if needed

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable unzip

      - name: Setup ChromeDriver using WebDriver Manager
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run setup script
        run: bash setup.sh

      - name: Run OXFUN Vault script
        working-directory: src/analysis
        run: |
          source ../../venv/bin/activate
          python oxfun_vault.py

      - name: Run Analyse Data script
        working-directory: src/analysis
        run: |
          source ../../venv/bin/activate
          python analyse_data.py

      - name: Commit and push updated data and reports
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Daily run: $(date '+%Y-%m-%d') - Updated data and reports with new files"
          git push
